### PR TITLE
Add simplifying functions.

### PR DESCRIPTION
**Pull request by amrsoll**
This is almost an esthetics change, it should be completely cross-compatible!

### CODE REVIEW

**Comment by tatsujb** [comment]
the parameters were actually inverted : 
 $1  is actually the package to be installed and
 $2  is the condition

I corrected it to this :  

```
	if $2
	then 
		to_log "T1 $1 is already installed, proceeding..." 
	else
		to_log "T1 $1 was not yet installed, installing..." 
		to_be_installed="$to_be_installed $1"
	fi
```

**Comment by tatsujb** [comment]
somethings up with the passed aruments of the to_be_installed function. I'm working on it now.

**Comment by amrsoll** [comment]
I know what it is. $1 is detected correctly only if there is no $2 (because $1 doesn't print anything for tests). I'm trying to figure out how to do it too. I believe it might require piping.

**Comment by tatsujb** [comment]
this is what I fixed it to : 

```
# bengining of find missing dependencies
to_be_installed=""

if_not_then_install() {
	# $1  is the package to be installed
	# $2  is the condition
	if $2
	then 
		to_log "T1 $1 is already installed, proceeding..." 
	else
		to_log "T1 $1 was not yet installed, installing..." 
		to_be_installed="$to_be_installed $1"
	fi
}

if [ $(command -v steam) ];
then
    to_log "T1 steam is already installed, proceeding..." 
else
    to_log "T1 steam was not yet installed, installing..." 
    [ "$operating_system" = "Debian GNU/Linux" ] && usermod -a -G video,audio $real_user
    [ "$operating_system" = "Debian GNU/Linux" ] && dpkg --add-architecture i386
    to_be_installed="$to_be_installed steam"
fi
if [ $(command -v steamcmd) ]
then
    to_log "T1 steam CMD is already installed, proceeding..." 
else
    to_log "T1 steam CMD was not yet installed, installing..." 
    if [ "'$operating_system'" = "Debian GNU/Linux" ]
    then
        if getent passwd steam > /dev/null 2>&1
        then
	    echo "steam home already exists"
        else
	    useradd -m steam
            ln -s /usr/games/steamcmd /home/steam/steamcmd
        fi
    fi
    to_be_installed="$to_be_installed steamcmd"
fi
if_not_then_install "procps" "[ -f /bin/kill ]"
if_not_then_install "xterm" "[ $(command -v xterm) ]"
if_not_then_install "whiptail" "[ $(command -v whiptail) ]"
if_not_then_install "pv" "[ $(command -v pv) ]"
if_not_then_install "curl" "[ $(command -v curl) ]"
if_not_then_install "jq" "[ $(command -v jq) ]"
if_not_then_install "zenity" "dpkg-query -W -f='${Status}' zenity | grep 'ok installed'" 
if_not_then_install "lib32gcc1" "dpkg-query -W -f='${Status}' lib32gcc1 | grep 'ok installed'"
if [ "$operating_system" = "Ubuntu" ]
then
if_not_then_install "gnome-terminal" "[ $(command -v gnome-terminal) ]" 
fi
# end of find missing dependencies
```

I inverted the two arguments because that's more robust :  `` (empty), wont count as an argument and if ever it messes up the condition or the text byproduct of the condition being resolved ends up being what is put into the to_be_installed variable. if you inverse the args order it's impossible for that to happen.

also I don't resolve the conditions before sending to the function i leave the condition between double quotes which passes the arg as a string but since it's double quotes it is still "interpretable" string so when if is asked to read it, it resolves it instead of seeing a string. Yet another layer of robustness.

I didn't bother inverting the order of the if because when I tested it it worked correctly but I'm pretty sure that because of the way the dpkg hack works we'll end up having to have a "negative first" if case for this function in order to refactor both the

**Comment by amrsoll** [comment]
Ah ok I thought that it would be interpreted as a `if <string>` and wouldn't make sense but it's good that it works :) sorry for the screwup my testing wasn't done properly..

**Comment by tatsujb** [comment]
no worries. I'm happy to have a contributor :) !

**Pull request merged**
